// Default curriculum structure for Ghanaian schools
export const DEFAULT_CURRICULUM = [
  {
    className: 'KG 1',
    subjects: ['Numeracy', 'Literacy', 'Creative Arts', 'Our World and Our People'],
  },
  {
    className: 'KG 2',
    subjects: ['Numeracy', 'Literacy', 'Creative Arts', 'Our World and Our People'],
  },
  {
    className: 'Basic 1',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Our World and Our People',
      'History of Ghana',
      'Ghanaian Language',
      'Religious and Moral Education',
      'Creative Arts',
      'Physical Education',
    ],
  },
  {
    className: 'Basic 2',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Our World and Our People',
      'History of Ghana',
      'Ghanaian Language',
      'Religious and Moral Education',
      'Creative Arts',
      'Physical Education',
    ],
  },
  {
    className: 'Basic 3',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Our World and Our People',
      'History of Ghana',
      'Ghanaian Language',
      'Religious and Moral Education',
      'Creative Arts',
      'Physical Education',
    ],
  },
  {
    className: 'Basic 4',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Our World and Our People',
      'History of Ghana',
      'Ghanaian Language',
      'Religious and Moral Education',
      'Creative Arts',
      'Physical Education',
      'French',
      'Computing',
    ],
  },
  {
    className: 'Basic 5',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Our World and Our People',
      'History of Ghana',
      'Ghanaian Language',
      'Religious and Moral Education',
      'Creative Arts',
      'Physical Education',
      'French',
      'Computing',
    ],
  },
  {
    className: 'Basic 6',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Our World and Our People',
      'History of Ghana',
      'Ghanaian Language',
      'Religious and Moral Education',
      'Creative Arts',
      'Physical Education',
      'French',
      'Computing',
    ],
  },
  {
    className: 'Basic 7',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Social Studies',
      'Computing',
      'Creative Arts and Design',
      'Career Technology',
      'Religious and Moral Education',
      'Ghanaian Language',
      'Physical Education and Health',
    ],
  },
  {
    className: 'Basic 8',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Social Studies',
      'Computing',
      'Creative Arts and Design',
      'Career Technology',
      'Religious and Moral Education',
      'Ghanaian Language',
      'Physical Education and Health',
    ],
  },
  {
    className: 'Basic 9',
    subjects: [
      'English Language',
      'Mathematics',
      'Science',
      'Social Studies',
      'Computing',
      'Creative Arts and Design',
      'Career Technology',
      'Religious and Moral Education',
      'Ghanaian Language',
      'Physical Education and Health',
    ],
  },
];
