import { ColumnDefinition, ModuleConfig } from './types';

/**
 * Column definitions for all modules
 * Each module defines its accepted columns and validation rules
 */

const studentColumns: ColumnDefinition[] = [
  {
    csvHeader: 'student_id',
    displayName: 'Student ID',
    description: 'Unique identifier for the student (UUID format)',
    required: false,
    dataType: 'uuid',
    example: '550e8400-e29b-41d4-a716-446655440000',
  },
  {
    csvHeader: 'admission_number',
    displayName: 'Admission Number',
    description: 'Unique admission number for duplicate checking',
    required: true,
    dataType: 'string',
    maxLength: 50,
    example: 'ADM-2024-001',
  },
  {
    csvHeader: 'first_name',
    displayName: 'First Name',
    description: 'Student first name',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'John',
  },
  {
    csvHeader: 'last_name',
    displayName: 'Last Name',
    description: 'Student last name',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'Doe',
  },
  {
    csvHeader: 'middle_name',
    displayName: 'Middle Name',
    description: 'Student middle name (optional)',
    required: false,
    dataType: 'string',
    maxLength: 100,
    example: 'Michael',
  },
  {
    csvHeader: 'gender',
    displayName: 'Gender',
    description: 'Student gender',
    required: true,
    dataType: 'enum',
    enumValues: ['Male', 'Female'],
    example: 'Male',
  },
  {
    csvHeader: 'date_of_birth',
    displayName: 'Date of Birth',
    description: 'Student date of birth in YYYY-MM-DD format',
    required: true,
    dataType: 'date',
    format: 'YYYY-MM-DD',
    example: '2010-05-15',
  },
  {
    csvHeader: 'class',
    displayName: 'Class',
    description: 'Class name or code (must exist in system)',
    required: true,
    dataType: 'string',
    example: 'Primary 4A',
    relationship: {
      table: 'classes',
      column: 'class_name',
      displayColumn: 'class_name',
    },
  },
  {
    csvHeader: 'house',
    displayName: 'House',
    description: 'House assignment (optional)',
    required: false,
    dataType: 'string',
    maxLength: 50,
    example: 'Red House',
  },
  {
    csvHeader: 'email',
    displayName: 'Email',
    description: 'Student email address',
    required: false,
    dataType: 'email',
    example: 'john.doe@school.com',
  },
  {
    csvHeader: 'phone',
    displayName: 'Phone',
    description: 'Student phone number',
    required: false,
    dataType: 'phone',
    example: '+254712345678',
  },
  {
    csvHeader: 'address',
    displayName: 'Address',
    description: 'Student residential address',
    required: false,
    dataType: 'string',
    maxLength: 255,
    example: '123 School Street, Nairobi',
  },
  {
    csvHeader: 'guardian_name',
    displayName: 'Guardian Name',
    description: 'Parent or guardian name',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'Jane Doe',
  },
  {
    csvHeader: 'guardian_phone',
    displayName: 'Guardian Phone',
    description: 'Parent or guardian phone number',
    required: true,
    dataType: 'phone',
    example: '+254712345678',
  },
  {
    csvHeader: 'status',
    displayName: 'Status',
    description: 'Student status in the system',
    required: true,
    dataType: 'enum',
    enumValues: ['Active', 'Inactive', 'Transferred', 'Graduated'],
    example: 'Active',
  },
];

const teacherColumns: ColumnDefinition[] = [
  {
    csvHeader: 'employee_id',
    displayName: 'Employee ID',
    description: 'Unique employee/teacher ID (UUID format)',
    required: false,
    dataType: 'uuid',
    example: '550e8400-e29b-41d4-a716-446655440001',
  },
  {
    csvHeader: 'first_name',
    displayName: 'First Name',
    description: 'Teacher first name',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'Jane',
  },
  {
    csvHeader: 'last_name',
    displayName: 'Last Name',
    description: 'Teacher last name',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'Smith',
  },
  {
    csvHeader: 'email',
    displayName: 'Email',
    description: 'Teacher email address',
    required: true,
    dataType: 'email',
    example: 'jane.smith@school.com',
  },
  {
    csvHeader: 'phone',
    displayName: 'Phone',
    description: 'Teacher phone number',
    required: true,
    dataType: 'phone',
    example: '+254712345678',
  },
  {
    csvHeader: 'qualification',
    displayName: 'Qualification',
    description: 'Academic qualification (e.g., BEd, MEd)',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'BEd (Mathematics)',
  },
  {
    csvHeader: 'employment_type',
    displayName: 'Employment Type',
    description: 'Type of employment',
    required: true,
    dataType: 'enum',
    enumValues: ['Permanent', 'Contract', 'Probation', 'Part-time'],
    example: 'Permanent',
  },
  {
    csvHeader: 'date_joined',
    displayName: 'Date Joined',
    description: 'Date teacher joined in YYYY-MM-DD format',
    required: true,
    dataType: 'date',
    format: 'YYYY-MM-DD',
    example: '2020-01-15',
  },
  {
    csvHeader: 'status',
    displayName: 'Status',
    description: 'Current employment status',
    required: true,
    dataType: 'enum',
    enumValues: ['Active', 'Inactive', 'On Leave', 'Resigned'],
    example: 'Active',
  },
];

const classColumns: ColumnDefinition[] = [
  {
    csvHeader: 'class_name',
    displayName: 'Class Name',
    description: 'Name of the class (e.g., Primary 4A)',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'Primary 4A',
  },
  {
    csvHeader: 'class_code',
    displayName: 'Class Code',
    description: 'Short code for the class',
    required: true,
    dataType: 'string',
    maxLength: 20,
    example: 'P4A',
  },
  {
    csvHeader: 'level',
    displayName: 'Level/Grade',
    description: 'Grade or level of the class',
    required: true,
    dataType: 'string',
    maxLength: 50,
    example: 'Primary 4',
  },
  {
    csvHeader: 'stream',
    displayName: 'Stream',
    description: 'Stream or section (A, B, C, etc.)',
    required: true,
    dataType: 'string',
    maxLength: 10,
    example: 'A',
  },
  {
    csvHeader: 'class_teacher',
    displayName: 'Class Teacher',
    description: 'Name of the class teacher',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'Jane Smith',
  },
  {
    csvHeader: 'capacity',
    displayName: 'Capacity',
    description: 'Maximum capacity of the class',
    required: true,
    dataType: 'number',
    example: '40',
  },
  {
    csvHeader: 'academic_year',
    displayName: 'Academic Year',
    description: 'Academic year (e.g., 2024-2025)',
    required: true,
    dataType: 'string',
    maxLength: 20,
    example: '2024-2025',
  },
];

const subjectColumns: ColumnDefinition[] = [
  {
    csvHeader: 'subject_name',
    displayName: 'Subject Name',
    description: 'Name of the subject',
    required: true,
    dataType: 'string',
    maxLength: 100,
    example: 'Mathematics',
  },
  {
    csvHeader: 'subject_code',
    displayName: 'Subject Code',
    description: 'Short code for the subject',
    required: true,
    dataType: 'string',
    maxLength: 20,
    example: 'MATH',
  },
  {
    csvHeader: 'department',
    displayName: 'Department',
    description: 'Department the subject belongs to',
    required: false,
    dataType: 'string',
    maxLength: 100,
    example: 'Science',
  },
  {
    csvHeader: 'description',
    displayName: 'Description',
    description: 'Subject description',
    required: false,
    dataType: 'string',
    maxLength: 500,
    example: 'Core mathematics subject',
  },
];

// Module configurations - each module specifies its columns and sample data
export const moduleConfigs: Record<string, ModuleConfig> = {
  students: {
    moduleName: 'Students',
    columns: studentColumns,
    sampleData: [
      {
        admission_number: 'ADM-2024-001',
        first_name: 'John',
        last_name: 'Doe',
        middle_name: 'Michael',
        gender: 'Male',
        date_of_birth: '2010-05-15',
        class: 'Primary 4A',
        house: 'Red House',
        email: 'john.doe@school.com',
        phone: '+254712345678',
        address: '123 School Street, Nairobi',
        guardian_name: 'Jane Doe',
        guardian_phone: '+254712345678',
        status: 'Active',
      },
      {
        admission_number: 'ADM-2024-002',
        first_name: 'Mary',
        last_name: 'Smith',
        middle_name: 'Elizabeth',
        gender: 'Female',
        date_of_birth: '2010-07-22',
        class: 'Primary 4A',
        house: 'Blue House',
        email: 'mary.smith@school.com',
        phone: '+254712345679',
        address: '456 Academy Road, Nairobi',
        guardian_name: 'Robert Smith',
        guardian_phone: '+254712345679',
        status: 'Active',
      },
      {
        admission_number: 'ADM-2024-003',
        first_name: 'Peter',
        last_name: 'Johnson',
        middle_name: 'David',
        gender: 'Male',
        date_of_birth: '2010-09-10',
        class: 'Primary 4B',
        house: 'Green House',
        email: 'peter.johnson@school.com',
        phone: '+254712345680',
        address: '789 Learning Lane, Nairobi',
        guardian_name: 'Sarah Johnson',
        guardian_phone: '+254712345680',
        status: 'Active',
      },
    ],
    primaryKey: 'admission_number',
    duplicateCheckFields: ['admission_number', 'email'],
    supportsUpdate: true,
    supportsBulkOps: ['delete', 'archive', 'activate', 'deactivate', 'assign_class'],
  },
  teachers: {
    moduleName: 'Teachers',
    columns: teacherColumns,
    sampleData: [
      {
        first_name: 'Jane',
        last_name: 'Smith',
        email: 'jane.smith@school.com',
        phone: '+254712345678',
        qualification: 'BEd (Mathematics)',
        employment_type: 'Permanent',
        date_joined: '2020-01-15',
        status: 'Active',
      },
      {
        first_name: 'David',
        last_name: 'Wilson',
        email: 'david.wilson@school.com',
        phone: '+254712345679',
        qualification: 'BEd (English)',
        employment_type: 'Permanent',
        date_joined: '2019-08-20',
        status: 'Active',
      },
      {
        first_name: 'Angela',
        last_name: 'Brown',
        email: 'angela.brown@school.com',
        phone: '+254712345680',
        qualification: 'BEd (Science)',
        employment_type: 'Contract',
        date_joined: '2022-03-01',
        status: 'Active',
      },
    ],
    primaryKey: 'email',
    duplicateCheckFields: ['email', 'phone'],
    supportsUpdate: true,
    supportsBulkOps: ['delete', 'deactivate', 'activate', 'assign_class'],
  },
  classes: {
    moduleName: 'Classes',
    columns: classColumns,
    sampleData: [
      {
        class_name: 'Primary 4A',
        class_code: 'P4A',
        level: 'Primary 4',
        stream: 'A',
        class_teacher: 'Jane Smith',
        capacity: 40,
        academic_year: '2024-2025',
      },
      {
        class_name: 'Primary 4B',
        class_code: 'P4B',
        level: 'Primary 4',
        stream: 'B',
        class_teacher: 'David Wilson',
        capacity: 42,
        academic_year: '2024-2025',
      },
      {
        class_name: 'Primary 5A',
        class_code: 'P5A',
        level: 'Primary 5',
        stream: 'A',
        class_teacher: 'Angela Brown',
        capacity: 38,
        academic_year: '2024-2025',
      },
    ],
    primaryKey: 'class_code',
    duplicateCheckFields: ['class_name', 'academic_year'],
    supportsUpdate: true,
    supportsBulkOps: ['delete', 'deactivate'],
  },
  subjects: {
    moduleName: 'Subjects',
    columns: subjectColumns,
    sampleData: [
      {
        subject_name: 'Mathematics',
        subject_code: 'MATH',
        department: 'Science',
        description: 'Core mathematics subject covering algebra and geometry',
      },
      {
        subject_name: 'English Language',
        subject_code: 'ENG',
        department: 'Languages',
        description: 'English language and literature studies',
      },
      {
        subject_name: 'Science',
        subject_code: 'SCI',
        department: 'Science',
        description: 'Integrated science covering biology, chemistry, and physics',
      },
    ],
    primaryKey: 'subject_code',
    duplicateCheckFields: ['subject_code', 'subject_name'],
    supportsUpdate: true,
    supportsBulkOps: ['delete', 'deactivate'],
  },
};

export function getModuleConfig(moduleName: string): ModuleConfig | null {
  return moduleConfigs[moduleName] || null;
}
